OmniDrome/Controllers/DBoardController.cs
using OmniDrome.DataAccessLayer;
using OmniDrome.Models;
using OmniDrome.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace OmniDrome.Controllers
{
    public class DBoardController : Controller
    {
        private PersonalInfoERPDAL db = new PersonalInfoERPDAL();
        // GET: DBoard
        public ActionResult Index()
        {

            return View();
        }

        [ChildActionOnly]
        public ActionResult DashBoard_Users()
        {

            var backgroundInfoes = db.BackgroundInfoes.Include(b => b.UserInfo);
            return View(backgroundInfoes.ToList());
        }

        //Data that is to be displayed in th Pie Chrt
        public JsonResult GetPieChartData()
        {

            var data = new[] { new { Name = "IT", Value = 25000 }, 
                                new { Name = "Pharma", Value = 5418 },
                                new { Name = "Technician", Value = 8457 },
                                new { Name = "Teachers", Value = 12457 },
                                new { Name = "Others", Value = 874 },};

            return Json(data);
        }

       [ChildActionOnly]
        public ActionResult DashboardItem_SalesPie()
        {
            return View();
        }


       
        //this is used with User Infoes table
        [ChildActionOnly]
       public ActionResult UserInfoTable()
       {
           //var userInfoes = db.UserInfoes.Include(b => b.UserInfo);
           //return View(UserInfoes.ToList());
           var userInfos = db.UserInfoes;
           return View(userInfos.ToList());
       }
       //summ
       //public ActionResult MyChartOwn(int? page)
       //{
       //    var model = new ChartViewModel
       //    {
       //        Chart = GetChart()
       //    };
       //    return View(model);
       //}
       private Chart GetChart()
       {
           return new Chart(600, 400, ChartTheme.Blue)
               .AddTitle("Number of website readers")
               .AddLegend()
               .AddSeries(
                   name: "WebSite",
                   chartType: "Pie",
                   xValue: new[] { "Digg", "DZone", "DotNetKicks", "StumbleUpon" },
                   yValues: new[] { "150000", "180000", "120000", "250000" });

       }


    }
}

OmniDrome/Views/DBoard/DashBoard_Users.cshtml
@model IEnumerable<OmniDrome.Models.BackgroundInfo>


<div class="dashboardItem">
    <div class="dashboardItemHeader">BackGround Informations</div>
    <div class="dashboardItemBody">
        <table class="tbl">
            <thead>
                <tr>
                    <th>EMail</th>
                    <th>Start Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td style="color:black">
                            @Html.DisplayFor(modelItem => item.UserInfo.Email)
                        </td>

                        <td style="color:black">
                            @Html.DisplayFor(modelItem => item.startDate)
                        </td>
                    </tr>
                }


            </tbody>
        </table>
    </div>
</div>

OmniDrome/Views/DBoard/DashboardItem_SalesPie.cshtml
<script type="text/javascript">

    google.load("visualization", "1", { packages: ["corechart"] });
    google.setOnLoadCallback(drawSalesChart);

    function drawSalesChart() {

        $.post('@Url.Content("~/DBoard/GetPieChartData") ', {},
            function (data) {
                var tdata = new google.visualization.DataTable();

                tdata.addColumn('string', 'Country');
                tdata.addColumn('number', 'Population');

                for (var i = 0; i < data.length; i++) {
                    tdata.addRow([data[i].Name, data[i].Value]);
                }

                var options = {
                    title: "Top 5 Jobs Category"
                };

                var chart = new google.visualization.PieChart(document.getElementById('chartSales'));
                chart.draw(tdata, options);
            });

    }
    </script>
<div class="dashboardItem">
    <div class="dashboardItemHeader">Jobs Category</div>
    <div class="dashboardItemBody">
        <div id="chartSales" style="">
            <div class="ajaxLoading"></div>
        </div>
    </div>
</div>    
    

OmniDrome/Views/DBoard/Details.cshtml
@model IEnumerable<OmniDrome.Models.PersonalDetails>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserInfo.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.firstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contactNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.profession)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.currentCity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.currentCountry)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.imageUrl)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserInfo.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.firstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contactNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.profession)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.currentCity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.currentCountry)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dateOfBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.imageUrl)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

OmniDrome/Views/DBoard/Index.cshtml
 
    <script src="@(Url.Content("~/Scripts/jquery-1.10.2.min.js"))" type="text/javascript"></script>

    <link href="@(Url.Content("~/Content/CssForDashBoard.css"))" rel="stylesheet" type="text/css" />
    <link href="@(Url.Content("~/Content/dashboard.css"))" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>


<body>
    
    <div class="pageBody">
        <div class="dashboard">
            <div class="dashboard3Col">
                <div class="dashboardCol">
                    @{ Html.RenderAction("DashBoard_Users", "DBoard");}

                    @*@{ Html.RenderAction("DashBoardItem_SalesPie", "DBoard");}*@

                </div>
                <div class="dashboardCol">
                    @{ Html.RenderAction("DashboardItem_SalesPie", "DBoard");}

                   
                   
                   

                </div>
                <div class="dashboardCol">
                    @{Html.RenderAction("UserInfoTable","DBoard");}

                    <div class="dashboardFooter"></div>

                </div>
               
            </div>
        </div>
    </div>
    
</body>
</html>

OmniDrome/Views/DBoard/MyChartOwn.cshtml
@model OmniDrome.ViewModels.ChartViewModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2>Our Awesome Chart!</h2>
    @Model.Chart.Write(format: "png")
</body>
</html>

OmniDrome/Views/DBoard/SearchForUser.cshtml
@model OmniDrome.Models.PersonalDetails

<div>
    <h4>PersonalDetails</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserInfo.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserInfo.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.profession)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.profession)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.currentCity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.currentCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.currentCountry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.currentCountry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imageUrl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OmniDrome/Views/DBoard/UserInDB.cshtml
@model IEnumerable<OmniDrome.Models.BackgroundInfo>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserInfo.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.startDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.endDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isCurrentPosition)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserInfo.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.startDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.endDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isCurrentPosition)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

OmniDrome/Views/DBoard/UserInfoTable.cshtml
@model IEnumerable<OmniDrome.Models.UserInfo>


<div class="dashboardItem">
    <div class="dashboardItemHeader">New Users</div>
    <div class="dashboardItemBody">
        <table class="tbl">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Date of Registration</th>
                </tr>
                
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td style="color:black">
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td style="color:black">
                            @Html.DisplayFor(modelItem => item.RegisterDate)
                        </td>
                        <td>

                            @Html.ActionLink("Details", "Details", new { id = item.Id })

                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>